In [2]:
import pandas as pd
linkGit="https://github.com/Journey-of-Success/TAREA-2/raw/main/dataUN_1.csv"
df=pd.read_csv(linkGit)

In [3]:
df

,Nº,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank for 2020
0,1.0,Switzerland,962.0,84.0,16.5,13.9,66933.0,5.0,3.0
1,2.0,Norway,961.0,83.2,18.2,13.0,64660.0,6.0,1.0
2,3.0,Iceland,959.0,82.7,19.2,13.8,55782.0,11.0,2.0
3,4.0,"Hong Kong, China (SAR)",952.0,85.5,17.3,12.2,62607.0,6.0,4.0
4,5.0,Australia,951.0,84.5,21.1,12.7,49238.0,18.0,5.0
...,...,...,...,...,...,...,...,...,...
189,187.0,Burundi,426.0,61.7,10.7,3.1,732.0,4.0,187.0
190,188.0,Central African Republic,404.0,53.9,8.0,4.3,966.0,1.0,188.0
191,189.0,Niger,400.0,61.6,7.0,2.1,1240.0,-3.0,189.0
192,190.0,Chad,394.0,52.5,8.0,2.6,1364.0,-7.0,190.0
193,191.0,South Sudan,385.0,55.0,5.5,5.7,768.0,-1.0,191.0